name: ESlint
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  run-prettier:
    name: Run ESlint
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60
    defaults:
      run:
        working-directory: .
    # env:
    #   KERIA_IMAGE_TAG: ${{ matrix.keria-version }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install deps
        run: |
          npm cache clean --force
          npm set registry https://registry.npmjs.org/
          npm ci
      - name: run eslint
        run: npm run lint
