name: Singlesig Multi-User Vlei Verifier Router Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**' # Run Validate Build on all PR branches
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test-multiple-aids-singlesig-vlei-verifier-router:
    name: Run singlesig multi-user test vlei-verifier-router using keria:${{ matrix.keria-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: .
    strategy:
      matrix:
        keria-version: ['0.2.0-dev3']
        node-version: ['20']
    env:
      KERIA_IMAGE_TAG: ${{ matrix.keria-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm set registry https://registry.npmjs.org/
          npm ci

      - name: Run docker
        run: |
          docker compose -f docker-compose-router.yaml down -v
          docker compose -f docker-compose-router.yaml up -d --pull always

      - name: Build
        run: npm run build

      - name: Run workflow
        run: WORKFLOW=singlesig-multi-user-vlei-verifier-router-test.yaml CONFIGURATION=configuration-singlesig-multi-user-vlei-verifier-router-test.json npx jest ./run-workflow.test.ts --runInBand --detectOpenHandles --forceExit
