name: Validate Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  validate-build:
    name: Validate Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        working-directory: .
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: ['20']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm set registry https://registry.npmjs.org/
          npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run pretty:check

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm test -- --runInBand --watchAll=false --runTestsByPath ./test/unit/utils.test.ts
